# fly.toml app configuration file generated for moviedescription on 2025-06-07T14:41:14+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moviedescription'
primary_region = 'arn'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
